######################################
# Makefile for TDHCP
#

#set this if you want a debugable version
CFLAGS=-Wall -g

#or alternatively this if you want a release build
#CFLAGS=-O2
#LDFLAGS=-s

#set this if you want allocation errors to end the process
CFLAGS += -DALLOCPANIC=1

#compiler and linker to use
CC=gcc
LD=gcc

#end of options
#####################

COMMON=common.o md5.o sock.o message.o

all: tdhcpc tdhcpd

tdhcpc: client.o $(COMMON)
	$(LD) $(LDFLAGS) -o $@ $^

tdhcpd: server.o $(COMMON)
	$(LD) $(LDFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	rm -rf *~ *.o core* svnrev.h

distclean: clean
	rm -rf tdhcpc tdhcpd .deps

deps:
	rm -f .deps
	for i in *.c ; do $(CC) -MM -MG $$i >>.deps ; done

client.o server.o: svnrev.h
svnrev.h: $(shell ls *.c *.h|grep -v svnrev)
	echo "/*Autogenerated File*/" >$@
	echo "#define SVNREV \"`svn info .|grep Revision:|cut -c 11-`\"" >>$@

include .deps

#make empty deps file for non-developers
.deps:
	touch .deps

.PHONY: clean deps